export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODCUT_SUCCESFULLY = 'ADD_PRODCUT_SUCCESFULLY'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'

export const START_DOWNLOAD_PRODUCTS = 'START_DOWNLOAD_PRODUCTS'
export const DOWNLOAD_PRODUCTS_SUCCESS = 'DOWNLOAD_PRODUCTS_SUCCESS'
export const DOWNLOAD_PRODUCTS_ERROR = 'DOWNLOAD_PRODUCTS_ERROR'


export const GET_PRODUCT_DELETE = 'GET_PRODUCT_DELETE'
export const PRODUCT_DELETE_SUCCES = 'PRODUCT_DELETE_SUCCES'
export const PRODUCT_DELETE_ERROR = 'PRODUCT_DELETE_ERROR'

export const GET_PRODUCT_EDIT = 'GET_PRODUCT_EDIT'
export const START_EDIT_PRODUCT = 'START_EDIT_PRODUCT'
export const PRODUCT_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS'
export const PRODUCT_EDIT_ERROR = 'PRODUCT_EDIT_ERROR'




